url: "https://vikaslazarus.github.io/AURA/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.


collections:
  destinations:
    output: true  
  team:
    output: true   